Revert "Allow macro calls anywhere in declaration crate"
If a module contained more than one separate `use` from the same
implementation crate:

    error: `proc_macro_hack_macroname` is already in scope
      --> src/lib.rs:10:1
       |
    10 | #[proc_macro_hack]
       | ^^^^^^^^^^^^^^^^^^
       |
       = note: macro-expanded `#[macro_use]`s may not shadow existing macros (see RFC 1560)
       = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

This reverts commit b928826d4c246ad0f186ec2b644f2ad01a85221c.